#!/usr/bin/env python3
"""
Subass Extra Stats
Supports: ASS, SRT, VTT formats
"""

import argparse
import json
import os
import re
import sys
from datetime import datetime
from pathlib import Path

try:
    import requests
except ImportError:
    print("Error: 'requests' library not found. Install with: pip3 install requests", file=sys.stderr)
    sys.exit(1)


# Firestore configuration
FIRESTORE_PROJECT = "subass-b5c64"
FIRESTORE_BASE_URL = f"https://firestore.googleapis.com/v1/projects/{FIRESTORE_PROJECT}/databases/(default)/documents"

# Supabase configuration
SUPABASE_URL = "https://mbqerzxljauitvkpvhbu.supabase.co"
SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1icWVyenhsamF1aXR2a3B2aGJ1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzgwMTY2MTksImV4cCI6MjA5MzU5MjYxOX0.rt-t28aLVZf-WiSggiRtaD95ZihUH-CVp34BJBRTOgQ"
SUPABASE_FUNCTION = "upsert-user-stats"
SUPABASE_LEADERBOARD_FUNCTION = "ach-leader-stats"
SUPABASE_PROFILE_FUNCTION = "get-user-profile"
SUPABASE_TALENTS_FUNCTION = "get-all-talents"


def main():
    parser = argparse.ArgumentParser(description='Extra stats')
    parser.add_argument('--register', action='store_true', help='Register user usage')
    parser.add_argument('--script_title', help='Script title/version for registration')
    parser.add_argument('--machine_id', help='Unique machine identifier generated by REAPER', default='unknown_machine')
    parser.add_argument('--stats-file', dest='stats_file', help='Path to a JSON file containing ACHIEVEMENTS.stats')
    parser.add_argument('--get-leaderboard', action='store_true', help='Fetch leaderboard for specific achievement')
    parser.add_argument('--ach-prefix', help='Achievement ID for leaderboard')
    parser.add_argument('--page', type=int, default=1, help='Page number for leaderboard')
    parser.add_argument('--get-profile', help='Fetch detailed profile for specific machine_id')
    parser.add_argument('--get-talents', action='store_true', help='Fetch all talents list')
    parser.add_argument('--limit', type=int, default=20, help='Limit for talents fetch')
    parser.add_argument('--offset', type=int, default=0, help='Offset for talents fetch')
    parser.add_argument('--filters-file', help='Path to JSON file with filters')
    
    args = parser.parse_args()

    # Get system username & unique machine ID
    username = os.getenv('USER') or os.getenv('USERNAME') or 'unknown_user'
    safe_username = re.sub(r'[^\w\-]', '_', username)
    
    machine_id = args.machine_id
    
    # Clean machine ID to be alphanumeric (just in case)
    machine_id = re.sub(r'[^a-zA-Z0-9]', '', machine_id).lower()[:32]
    unique_user_id = f"{safe_username}_{machine_id}"

    # --- REGISTRATION MODE ---
    if args.register:
        if not args.script_title:
            print("Error: --script_title required for registration", file=sys.stderr)
            sys.exit(1)

        # --- Load achievements stats if provided ---
        stats_filtered = {}
        dubber_name = ""
        if args.stats_file:
            try:
                with open(args.stats_file, 'r', encoding='utf-8') as sf:
                    stats_raw = json.load(sf)
                stats_filtered = {k: v for k, v in stats_raw['stats'].items() if not k.endswith('_tracking')}
                dubber_name = stats_raw.get('dubber_name', '')
                dubber_bio = stats_raw.get('dubber_bio', '')
                dubber_contact = stats_raw.get('dubber_contact', '')
                dubber_specialization = stats_raw.get('dubber_specialization', '')
                dubber_archetypes = stats_raw.get('dubber_archetypes', '')
                dubber_samples = stats_raw.get('dubber_samples', '')
                dubber_equipment = stats_raw.get('dubber_equipment', '')
                dubber_conditions = stats_raw.get('dubber_conditions', '')
                dubber_voice = stats_raw.get('dubber_voice', '')
                dubber_timbre = stats_raw.get('dubber_timbre', '')
                dubber_vocals = stats_raw.get('dubber_vocals', '')
                dubber_status = stats_raw.get('dubber_status', '')
            except OSError as e:
                print(f"Warning: Could not read stats file: {e}", file=sys.stderr)
            except json.JSONDecodeError as e:
                print(f"Warning: Could not parse stats JSON: {e}", file=sys.stderr)

        safe_title = re.sub(r'[^\w\-]', '_', args.script_title)

        # Path: versions/<script_title>/users/<unique_user_id>
        # We need 4 segments for a valid document path: Col/Doc/Col/Doc
        # using 'versions' as root collection (allowed by rules)
        doc_path_user = f"{FIRESTORE_BASE_URL}/versions/{safe_title}/users/{unique_user_id}"

        # Build Firestore mapValue for stats (numbers → integerValue/doubleValue)
        def _to_firestore_value(v):
            if isinstance(v, float):
                return {"doubleValue": v}
            if isinstance(v, int):
                return {"integerValue": str(v)}
            return {"stringValue": str(v)}

        stats_map = {"mapValue": {"fields": {k: _to_firestore_value(v) for k, v in stats_filtered.items()}}}

        payload_user = {
            "fields": {
                "username": {"stringValue": username},
                "machine_id": {"stringValue": machine_id},
                "dubber_name": {"stringValue": dubber_name},
                "dubber_bio": {"stringValue": dubber_bio},
                "dubber_contact": {"stringValue": dubber_contact},
                "dubber_specialization": {"stringValue": dubber_specialization},
                "dubber_archetypes": {"stringValue": dubber_archetypes},
                "dubber_samples": {"stringValue": dubber_samples},
                "dubber_equipment": {"stringValue": dubber_equipment},
                "dubber_conditions": {"stringValue": dubber_conditions},
                "dubber_voice": {"stringValue": dubber_voice},
                "dubber_timbre": {"stringValue": dubber_timbre},
                "dubber_vocals": {"stringValue": dubber_vocals},
                "dubber_status": {"stringValue": dubber_status},
                "last_active": {"timestampValue": datetime.utcnow().strftime("%Y-%m-%dT%H:%M:%SZ")},
                "os": {"stringValue": sys.platform},
                "stats": stats_map,
            }
        }

        try:
            resp = requests.patch(
                doc_path_user,
                json=payload_user,
                headers={"Content-Type": "application/json"},
                timeout=10
            )

            if resp.status_code not in [200, 201]:
                print(f"Warning: Firestore registration failed with status {resp.status_code}", file=sys.stderr)
                sys.exit(1)

            print(f"✓ Firestore: {safe_title}/{safe_username}")

        except Exception as e:
            print(f"Error registering to Firestore: {e}", file=sys.stderr)
            sys.exit(1)

        # --- Supabase registration (INSERT-only, write-only table) ---
        try:
            supabase_payload = {
                "machine_id": machine_id,
                "username": username,
                "script_title": args.script_title,
                "os": sys.platform,
                "dubber_name": dubber_name,
                "dubber_bio": dubber_bio,
                "dubber_contact": dubber_contact,
                "dubber_specialization": dubber_specialization,
                "dubber_archetypes": dubber_archetypes,
                "dubber_samples": dubber_samples,
                "dubber_equipment": dubber_equipment,
                "dubber_conditions": dubber_conditions,
                "dubber_voice": dubber_voice,
                "dubber_timbre": dubber_timbre,
                "dubber_vocals": dubber_vocals,
                "dubber_status": dubber_status,
                "last_active": datetime.utcnow().strftime("%Y-%m-%dT%H:%M:%SZ"),
                "stats": stats_filtered,
            }

            supabase_headers = {
                "Content-Type": "application/json",
                "Authorization": f"Bearer {SUPABASE_ANON_KEY}",
            }
            resp_sb = requests.post(
                f"{SUPABASE_URL}/functions/v1/{SUPABASE_FUNCTION}",
                json=supabase_payload,
                headers=supabase_headers,
                timeout=10
            )
            
            output_path = Path(__file__).parent / "subass_rankings.json"
            if resp_sb.status_code in [200, 201]:
                result_data = resp_sb.json()
                result_data["ok"] = True
                with open(output_path, "w", encoding="utf-8") as f:
                    json.dump(result_data, f, indent=4, ensure_ascii=False)
                print(f"✓ Supabase: OK")
            else:
                error_msg = f"HTTP {resp_sb.status_code}: {resp_sb.text}"
                with open(output_path, "w", encoding="utf-8") as f:
                    json.dump({"ok": False, "error": error_msg}, f, indent=4, ensure_ascii=False)
                print(f"Warning: Supabase error: {error_msg}", file=sys.stderr)
        except Exception as e:
            error_msg = str(e)
            print(f"Warning: Supabase error: {error_msg}", file=sys.stderr)
            try:
                output_path = Path(__file__).parent / "subass_rankings.json"
                with open(output_path, "w", encoding="utf-8") as f:
                    json.dump({"ok": False, "error": error_msg}, f, indent=4, ensure_ascii=False)
            except:
                pass

        sys.exit(0)

    # --- LEADERBOARD MODE ---
    if args.get_leaderboard:
        if not args.ach_prefix:
            print("Error: --ach-prefix required for leaderboard", file=sys.stderr)
            sys.exit(1)

        try:
            supabase_payload = {
                "machine_id": machine_id,
                "ach_prefix": args.ach_prefix,
                "limit_count": 30,
                "page": args.page,
            }
            supabase_headers = {
                "Content-Type": "application/json",
                "Authorization": f"Bearer {SUPABASE_ANON_KEY}",
            }
            resp_sb = requests.post(
                f"{SUPABASE_URL}/functions/v1/{SUPABASE_LEADERBOARD_FUNCTION}",
                json=supabase_payload,
                headers=supabase_headers,
                timeout=15
            )
            if resp_sb.status_code == 200:
                result_data = resp_sb.json()
                result_data["ok"] = True
                output_path = Path(__file__).parent / "subass_leaderboard.json"
                with open(output_path, "w", encoding="utf-8") as f:
                    json.dump(result_data, f, indent=4, ensure_ascii=False)
                print(f"✓ Leaderboard: OK (Saved to {output_path.name})")
            else:
                error_msg = f"HTTP {resp_sb.status_code}: {resp_sb.text}"
                output_path = Path(__file__).parent / "subass_leaderboard.json"
                with open(output_path, "w", encoding="utf-8") as f:
                    json.dump({"ok": False, "error": error_msg}, f, indent=4, ensure_ascii=False)
                print(f"Error: {error_msg}", file=sys.stderr)
                sys.exit(1)
        except Exception as e:
            error_msg = str(e)
            try:
                output_path = Path(__file__).parent / "subass_leaderboard.json"
                with open(output_path, "w", encoding="utf-8") as f:
                    json.dump({"ok": False, "error": error_msg}, f, indent=4, ensure_ascii=False)
            except:
                pass
            print(f"Error: {error_msg}", file=sys.stderr)
            sys.exit(1)
        sys.exit(0)

    # --- PROFILE DETAILS MODE ---
    if args.get_profile:
        try:
            supabase_payload = {
                "machine_id": args.get_profile,
            }
            supabase_headers = {
                "Content-Type": "application/json",
                "Authorization": f"Bearer {SUPABASE_ANON_KEY}",
            }
            resp_sb = requests.post(
                f"{SUPABASE_URL}/functions/v1/{SUPABASE_PROFILE_FUNCTION}",
                json=supabase_payload,
                headers=supabase_headers,
                timeout=15
            )
            
            output_path = Path(__file__).parent / "subass_profile_details.json"
            if resp_sb.status_code == 200:
                result_data = resp_sb.json()
                result_data["ok"] = True
                with open(output_path, "w", encoding="utf-8") as f:
                    json.dump(result_data, f, indent=4, ensure_ascii=False)
                print(f"✓ Profile: OK (Saved to {output_path.name})")
            else:
                error_msg = f"HTTP {resp_sb.status_code}: {resp_sb.text}"
                with open(output_path, "w", encoding="utf-8") as f:
                    json.dump({"ok": False, "error": error_msg}, f, indent=4, ensure_ascii=False)
                print(f"Error: {error_msg}", file=sys.stderr)
                sys.exit(1)
        except Exception as e:
            error_msg = str(e)
            print(f"Error: {error_msg}", file=sys.stderr)
            try:
                output_path = Path(__file__).parent / "subass_profile_details.json"
                with open(output_path, "w", encoding="utf-8") as f:
                    json.dump({"ok": False, "error": error_msg}, f, indent=4, ensure_ascii=False)
            except:
                pass
            sys.exit(1)
        sys.exit(0)
    
    # --- TALENT SEARCH MODE ---
    if args.get_talents:
        try:
            # Load filters from JSON file (safer for encoding)
            filters = {}
            if args.filters_file and os.path.exists(args.filters_file):
                try:
                    with open(args.filters_file, 'r', encoding='utf-8') as ff:
                        filters = json.load(ff)
                except Exception as e:
                    print(f"Warning: Could not read filters file: {e}", file=sys.stderr)
                finally:
                    # Delete the filters file after reading
                    if args.filters_file and os.path.exists(args.filters_file):
                        try:
                            os.remove(args.filters_file)
                        except:
                            pass

            supabase_payload = {
                "limit": args.limit,
                "offset": args.offset,
                "filters": filters
            }
            supabase_headers = {
                "Content-Type": "application/json",
                "Authorization": f"Bearer {SUPABASE_ANON_KEY}",
            }
            resp_sb = requests.post(
                f"{SUPABASE_URL}/functions/v1/{SUPABASE_TALENTS_FUNCTION}",
                json=supabase_payload,
                headers=supabase_headers,
                timeout=15
            )
            
            output_path = Path(__file__).parent / "subass_talents.json"
            if resp_sb.status_code == 200:
                result_data = resp_sb.json()
                result_data["ok"] = True
                with open(output_path, "w", encoding="utf-8") as f:
                    json.dump(result_data, f, indent=4, ensure_ascii=False)
                print(f"✓ Talents: OK (Saved to {output_path.name})")
            else:
                error_msg = f"HTTP {resp_sb.status_code}: {resp_sb.text}"
                with open(output_path, "w", encoding="utf-8") as f:
                    json.dump({"ok": False, "error": error_msg}, f, indent=4, ensure_ascii=False)
                print(f"Error: {error_msg}", file=sys.stderr)
                sys.exit(1)
        except Exception as e:
            error_msg = str(e)
            print(f"Error: {error_msg}", file=sys.stderr)
            try:
                output_path = Path(__file__).parent / "subass_talents.json"
                with open(output_path, "w", encoding="utf-8") as f:
                    json.dump({"ok": False, "error": error_msg}, f, indent=4, ensure_ascii=False)
            except:
                pass
            sys.exit(1)
        sys.exit(0)

    sys.exit(0)


if __name__ == '__main__':
    main()
