#!/usr/bin/env python3
"""
Subass Extra Stats - Upload subtitle analytics
Supports: ASS, SRT, VTT formats
"""

import argparse
import hashlib
import json
import os
import re
import sys
import uuid
from datetime import datetime
from pathlib import Path

try:
    import requests
except ImportError:
    print("Error: 'requests' library not found. Install with: pip3 install requests", file=sys.stderr)
    sys.exit(1)


# Firestore configuration
FIRESTORE_PROJECT = "subass-b5c64"
FIRESTORE_BASE_URL = f"https://firestore.googleapis.com/v1/projects/{FIRESTORE_PROJECT}/databases/(default)/documents"

# Supabase configuration
SUPABASE_URL = "https://mbqerzxljauitvkpvhbu.supabase.co"
SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1icWVyenhsamF1aXR2a3B2aGJ1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzgwMTY2MTksImV4cCI6MjA5MzU5MjYxOX0.rt-t28aLVZf-WiSggiRtaD95ZihUH-CVp34BJBRTOgQ"
SUPABASE_FUNCTION = "upsert-user-stats"


def calculate_md5(content):
    """Calculate MD5 hash of string content"""
    return hashlib.md5(content.encode('utf-8')).hexdigest()


def main():
    parser = argparse.ArgumentParser(description='Upload subtitle analytics to Firestore')
    parser.add_argument('--filepath', help='Full path to subtitle file (.ass, .srt, .vtt) [Required for stats]')
    parser.add_argument('--project_name', help='Project name (e.g., MyProject.RPP)')
    parser.add_argument('--register', action='store_true', help='Register user usage')
    parser.add_argument('--script_title', help='Script title/version for registration')
    parser.add_argument('--machine_id', help='Unique machine identifier generated by REAPER', default='unknown_machine')
    parser.add_argument('--stats-file', dest='stats_file', help='Path to a JSON file containing ACHIEVEMENTS.stats')
    
    args = parser.parse_args()

    # Get system username & unique machine ID
    username = os.getenv('USER') or os.getenv('USERNAME') or 'unknown_user'
    safe_username = re.sub(r'[^\w\-]', '_', username)
    
    machine_id = args.machine_id
    
    # Clean machine ID to be alphanumeric (just in case)
    machine_id = re.sub(r'[^a-zA-Z0-9]', '', machine_id).lower()[:32]
    unique_user_id = f"{safe_username}_{machine_id}"

    # --- REGISTRATION MODE ---
    if args.register:
        if not args.script_title:
            print("Error: --script_title required for registration", file=sys.stderr)
            sys.exit(1)

        # --- Load achievements stats if provided ---
        stats_filtered = {}
        if args.stats_file:
            try:
                with open(args.stats_file, 'r', encoding='utf-8') as sf:
                    stats_raw = json.load(sf)
                stats_filtered = {k: v for k, v in stats_raw.items() if not k.endswith('_tracking')}
            except OSError as e:
                print(f"Warning: Could not read stats file: {e}", file=sys.stderr)
            except json.JSONDecodeError as e:
                print(f"Warning: Could not parse stats JSON: {e}", file=sys.stderr)

        safe_title = re.sub(r'[^\w\-]', '_', args.script_title)

        # Path: versions/<script_title>/users/<unique_user_id>
        # We need 4 segments for a valid document path: Col/Doc/Col/Doc
        # using 'versions' as root collection (allowed by rules)
        doc_path_user = f"{FIRESTORE_BASE_URL}/versions/{safe_title}/users/{unique_user_id}"

        # Build Firestore mapValue for stats (numbers → integerValue/doubleValue)
        def _to_firestore_value(v):
            if isinstance(v, float):
                return {"doubleValue": v}
            if isinstance(v, int):
                return {"integerValue": str(v)}
            return {"stringValue": str(v)}

        stats_map = {"mapValue": {"fields": {k: _to_firestore_value(v) for k, v in stats_filtered.items()}}}

        payload_user = {
            "fields": {
                "username": {"stringValue": username},
                "machine_id": {"stringValue": machine_id},
                "last_active": {"timestampValue": datetime.utcnow().strftime("%Y-%m-%dT%H:%M:%SZ")},
                "os": {"stringValue": sys.platform},
                "stats": stats_map,
            }
        }

        try:
            resp = requests.patch(
                doc_path_user,
                json=payload_user,
                headers={"Content-Type": "application/json"},
                timeout=10
            )

            if resp.status_code not in [200, 201]:
                print(f"Warning: Firestore registration failed with status {resp.status_code}", file=sys.stderr)
                sys.exit(1)

            print(f"✓ Firestore: {safe_title}/{safe_username}")

        except Exception as e:
            print(f"Error registering to Firestore: {e}", file=sys.stderr)
            sys.exit(1)

        # --- Supabase registration (INSERT-only, write-only table) ---
        try:
            supabase_payload = {
                "machine_id": machine_id,
                "username": username,
                "script_title": args.script_title,
                "os": sys.platform,
                "last_active": datetime.utcnow().strftime("%Y-%m-%dT%H:%M:%SZ"),
                "stats": stats_filtered,
            }

            supabase_headers = {
                "Content-Type": "application/json",
                "Authorization": f"Bearer {SUPABASE_ANON_KEY}",
            }
            resp_sb = requests.post(
                f"{SUPABASE_URL}/functions/v1/{SUPABASE_FUNCTION}",
                json=supabase_payload,
                headers=supabase_headers,
                timeout=10
            )
            if resp_sb.status_code not in [200, 201]:
                print(f"Warning: Supabase error {resp_sb.status_code}: {resp_sb.text}", file=sys.stderr)
            else:
                # Зберігаємо результат у файл для Lua
                try:
                    result_data = resp_sb.json()
                    output_path = Path(__file__).parent / "subass_rankings.json"
                    with open(output_path, "w", encoding="utf-8") as f:
                        json.dump(result_data, f, indent=4, ensure_ascii=False)
                    print(f"✓ Supabase: OK (Results saved to {output_path.name})")
                except Exception as save_err:
                    print(f"Warning: Could not save rankings file: {save_err}", file=sys.stderr)
                    print(f"✓ Supabase: OK")
        except Exception as e:
            print(f"Warning: Supabase error: {e}", file=sys.stderr)

        sys.exit(0)

    # --- STATS MODE ---
    if not args.filepath or not args.project_name:
        print("Error: --filepath and --project_name required for stats upload", file=sys.stderr)
        parser.print_help()
        sys.exit(1)
    
    # Validate file exists
    if not os.path.isfile(args.filepath):
        print(f"Error: File not found: {args.filepath}", file=sys.stderr)
        sys.exit(1)
    
    try:
        # Read file content as-is
        with open(args.filepath, 'r', encoding='utf-8-sig') as f:
            file_content = f.read()
        
        if not file_content.strip():
            print("Warning: File is empty", file=sys.stderr)
            sys.exit(0)
        
        # Calculate MD5 of content
        md5_hash = calculate_md5(file_content)
        
        safe_filename = re.sub(r'[^\w\-]', '_', Path(args.filepath).stem)[:64]
        
        # Document IDs
        doc_id_subtitles = md5_hash
        doc_id_analytics = f"{safe_username}_{safe_filename}_{md5_hash}"
        
        # Document paths
        doc_path_subtitles = f"{FIRESTORE_BASE_URL}/subtitles/{doc_id_subtitles}"
        doc_path_analytics = f"{FIRESTORE_BASE_URL}/analytics/{doc_id_analytics}"
        
        # Prepare payloads
        payload_subtitles = {
            "fields": {
                "1_filename": {"stringValue": os.path.basename(args.filepath)},
                "2_content": {"stringValue": file_content}
            }
        }
        
        payload_analytics = {
            "fields": {
                "1_filename": {"stringValue": os.path.basename(args.filepath)},
                "2_project": {"stringValue": args.project_name},
                "3_user": {"stringValue": username},
                "4_timestamp": {"timestampValue": datetime.utcnow().strftime("%Y-%m-%dT%H:%M:%SZ")},
                "5_relation_to_subtitles": {"referenceValue": f"projects/{FIRESTORE_PROJECT}/databases/(default)/documents/subtitles/{doc_id_subtitles}"}
            }
        }
        
        # Upload analytics
        resp_sub = requests.patch(
            doc_path_subtitles,
            json=payload_subtitles,
            headers={"Content-Type": "application/json"},
            timeout=60
        )
        
        if resp_sub.status_code not in [200, 201]:
            print(f"Warning: Subtitles upload failed with status {resp_sub.status_code}", file=sys.stderr)
            sys.exit(1)
        
        # Upload analytics
        resp_ana = requests.patch(
            doc_path_analytics,
            json=payload_analytics,
            headers={"Content-Type": "application/json"},
            timeout=60
        )
        
        if resp_ana.status_code not in [200, 201]:
            print(f"Warning: Analytics upload failed with status {resp_ana.status_code}", file=sys.stderr)
            sys.exit(1)
        
        print(f"✓ Uploaded: MD5={md5_hash[:8]}... | Analytics={doc_id_analytics}")
        sys.exit(0)
        
    except requests.RequestException as e:
        print(f"Error uploading to Firestore: {e}", file=sys.stderr)
        sys.exit(1)
    except Exception as e:
        print(f"Error: {e}", file=sys.stderr)
        sys.exit(1)


if __name__ == '__main__':
    main()

